### ISSUE TITLE
Can't use downloaded csv history files

### ISSUE THREAD

**Issue by mikkkeldp** [ntrang086/q_learning_trading#1]
Hi, great repo!

I was running into a problem when I download the history of BTC-USD. I get the following error:

```
Traceback (most recent call last):
  File "StrategyLearner.py", line 300, in <module>
    stl.add_evidence(symbol=symbol, start_val=start_val, 
  File "StrategyLearner.py", line 181, in add_evidence
    thresholds = self.get_thresholds(df_features, self.num_steps)
  File "StrategyLearner.py", line 87, in get_thresholds
    thres[i, step] = df_copy[feat].iloc[(step + 1) * step_size]
  File "/home/mikkel/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 1768, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/mikkel/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 2138, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/mikkel/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py", line 2063, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by mikkkeldp** [comment]
I realized that the date is descending in your given examples and ascending in my downloaded yahoo csv. I also noticed that the last two columns where switched. After I fixed this manually, I still got this error. Any idea as to why this is happening?
